### ISSUE TITLE
Damage console.error when it's not supposed to?

### ISSUE THREAD

**Issue by Lawendt** [dramamine/leftovers-again#1]
I'm using the Damage object from /game/damage.js and when I call it, it send the current console error: "missing the stat I need: stats" for every stats that the pokemon should have. The problem is that the pokemon have the stats.
I modified the script to log the value inside the stat that it is trying to acess and after that I do an for (var index in mon.baseStats) just to see if all the stats are there.
What I got was this: 

![2016-10-03 20_03_13-npm](https://cloud.githubusercontent.com/assets/13232242/19057262/022f3082-89a5-11e6-8815-3d246a4d7f39.png)

so maybe it shouldn't log this error?

EDIT: Sorry, I updated the libs and now it doesn't help anymore. I just don't know how to close the issue :(

**Comment by dramamine** [comment]
Ha! No worries, glad it works now. I think only I can close issues.
