### ISSUE TITLE
Hidden Power damage calculation

### ISSUE THREAD

**Issue by kirliavc** [dramamine/leftovers-again#12]
Current damage calculator in ```game/damage.js``` doesn't check the hidden power type and always regard the move as normal type. 
Quick fix suggestion:
```js
if (move.name.indexOf('Hidden Power')!=-1){
        move.type=move.move.replace("Hidden Power ","");
    }
```

**Comment by dramamine** [comment]
Cool, I used your fix, this is in 0.11.7
