### ISSUE TITLE
Bot's Pokémon is maxed out despite .js file indicating otherwise

### ISSUE THREAD

**Issue by BeyondTheHorizon** [dramamine/leftovers-again#17]
I created a simple test JavaScript file indicating a single Level 5 Eevee but when I fight it, its stats are maxed out as if it were Level 100 with maximum EVs and its Level isn't shown on the screen in Showdown. This also happens with the example bots that come with this program. I tested with the trapper file. Here is my code for the (Gen 1) Eevee:

``Eevee``
``Level: 5``
``EVs: 1 HP / 1 Atk / 1 Def / 1 SpA / 1 SpD / 1 Spe``
``- Tackle``
``- Tail Whip``

**Comment by dramamine** [comment]
What battle type are you using with this? Just wondering because some battle types are going to force you into better stats.

Do you have the same problem if you set IVs like this?

**Comment by BeyondTheHorizon** [comment]
What are battle types? Are they "format" and "accepts"? If I think I understand you, I've tried different battle types and none fix it.

**Comment by dramamine** [comment]
Yeah, I'd set format to "anythinggoes".

I'll take a look later; looks like a bug to me.

**Comment by BeyondTheHorizon** [comment]
Today I started the program with --loglevel=5, and this is the information it came up with for the bot's Eevee:

``STATE:
{"self":{"active":{"condition":"250/250","statuses":[],"id":"eevee","species":"Eevee","moves":[{"move":"Tackle","id":"tackle","pp":56,"maxpp":56,"target":"normal","disabled":false,"accuracy":100,"basePower":40,"category":"Physical","flags":{"contact":1,"protect":1,"mirror":1},"name":"Tackle","priority":0,"secondary":false,"type":"Normal"},{"move":"Tail Whip","id":"tailwhip","pp":48,"maxpp":48,"target":"allAdjacentFoes","disabled":false,"accuracy":100,"basePower":0,"boosts":{"def":-1},"category":"Status","flags":{"protect":1,"reflectable":1,"mirror":1},"name":"Tail Whip","priority":0,"secondary":false,"type":"Normal"}],"gender":"M","hp":250,"maxhp":250,"hppct":100,"active":true,"types":["Normal"],"baseStats":{"hp":55,"atk":55,"def":50,"spa":45,"spd":65,"spe":55},"abilities":{"0":"Run Away","1":"Adaptability","H":"Anticipation"},"baseAbility":"none","stats":{"atk":129,"def":119,"spa":149,"spd":149,"spe":129},"position":"p1a","owner":"p1","prevMoves":[],"nickname":"Eevee","seenMoves":[],"boostedStats":{"atk":129,"def":119,"spa":149,"spd":149,"spe":129}},"reserve":[{"condition":"250/250","statuses":[],"id":"eevee","species":"Eevee","moves":[{"accuracy":100,"basePower":40,"category":"Physical","id":"tackle","name":"Tackle","flags":{"contact":1,"protect":1,"mirror":1},"target":"normal","type":"Normal"},{"accuracy":100,"category":"Status","id":"tailwhip","name":"Tail Whip","flags":{"protect":1,"reflectable":1,"mirror":1},"target":"allAdjacentFoes","type":"Normal"}],"gender":"M","hp":250,"maxhp":250,"hppct":100,"active":true,"types":["Normal"],"baseStats":{"hp":55,"atk":55,"def":50,"spa":45,"spd":65,"spe":55},"abilities":{"0":"Run Away","1":"Adaptability","H":"Anticipation"},"baseAbility":"none","stats":{"atk":129,"def":119,"spa":149,"spd":149,"spe":129},"position":"p1a","owner":"p1","prevMoves":[],"nickname":"Eevee","seenMoves":[],"boostedStats":{"atk":129,"def":119,"spa":149,"spd":149,"spe":129}}]}``

I'm not sure if this is helpful to you or not.

It also seems PP is also maxed out when I indicated no such thing in my JavaScript file.

**Comment by dramamine** [comment]
OK, I did find some problems with the team-reading code, it was not reading "level" at all and it was misreading the HP IV. Everything else should be okay. This is published in 0.11.6

I wrote a test for this too in teamSpec.js

Let me know if this doesn't fix your issue.

Also I don't think you can affect PP of your pokemon through Teambuilder?

**Comment by BeyondTheHorizon** [comment]
Seems to be working. Thank you so much!
