### ISSUE TITLE
Clones problem

### ISSUE THREAD

**Issue by BeyondTheHorizon** [dramamine/leftovers-again#18]
Hi again, I've been having a problem fighting a bot I programmed that has two of the same Pokémon (Dragonair) with identical Levels, EVs/IVs, and moves. When I KO one of them and the bot is about to send out the second, it either gets stuck on "Waiting for opponent..." or the bot forfeits with a "'dead' is true" error. Maybe the bot's getting confused somewhere? Oh, and it was set to switch to random Pokémon and use random moves.

**Comment by dramamine** [comment]
Do the mons have different nicknames? Their ident should be based on nickname + species + level.

**Comment by BeyondTheHorizon** [comment]
No, they don't have nicknames as I don't really bother with them, either in the games or here, mainly because I'm no good at coming up with any. Is there a way to create a ident for a mon?

**Comment by dramamine** [comment]
Yep, here's an example:
https://github.com/dramamine/leftovers-again/blob/master/src/bots/research/trapper.js#L46

Unique nicknames *should* fix your ident problem, I think this is something I was fighting with when I was developing the code.

**Comment by BeyondTheHorizon** [comment]
Yeah, I eventually decided to just nickname them "Dragonair A" and "Dragonair B". Very creative, I know—sarcasm—but it seemed to resolve it.
