### ISSUE TITLE
Wrong Pokemon data after mega-evolving?

### ISSUE THREAD

**Issue by Milkshanks** [dramamine/leftovers-again#2]
Hey Dramamine! First of all thanks for all the work you've put into leftovers-again! I've came across this issue where the bot i've been working on isn't able to detect when the opponent's mon has mega evolved. It still assumes all data (like types, abilities and stats) from the non evolved version of the mon, obviously messing the (already messed up) AI I've been working on, haha. Also, the battle logs on the log folder doesn't show the Pokemon as its mega self too, it just indicates whether it can mega evolve or not (canMegaEvo) at some point in the logs. Now I'm not really sure if this is really an issue or I'm missing something terribly obvious here, but I'm inclined to believe it's the former.

PS: I attached an image showing the issue for your viewing pleasure ;)

![image](https://cloud.githubusercontent.com/assets/13732389/19362152/dd7ec54a-915b-11e6-83eb-de19cebe71dc.png)

**Comment by dramamine** [comment]
Interesting! Yeah, I think I am not doing anything to record if an opponent's Pokemon has mega-evolved, yet. Marking this as a feature request...

**Comment by dramamine** [comment]
@Milkshanks this should be fixed in 0.9.3, please install the latest version and see if it's working as expected!
