### ISSUE TITLE
Gen 7 server?

### ISSUE THREAD

**Issue by skewbed** [dramamine/leftovers-again#8]
I am currently trying to set up a gen7anythinggoes bot. It says that that format does exist. I even copypasted the HTML ID of the Gen 7 Anything Goes in the official Pokemon Showdown format popup.

The main server git repo (by Zarel) seems not to work.

Is it possible to update your showdown server fork that is referenced in the docs?

**Comment by dramamine** [comment]
Ahh yeah, this fork was way behind (January-ish)
I updated the fork, and changed the generate.js script to use gen7 formats only. (0.11.3)

This command will run a gen7anythinggoes battle:
`npm start -- whynotbaut --opponent=stonedbirdie`
